### ISSUE TITLE
[BUG] No link from plugin to the Docs site

### ISSUE THREAD

**Issue by epugh** [opensearch-project/user-behavior-insights#18]
### What is the bug?
@hdhalter was skimming through the [UBI readme](https://github.com/opensearch-project/user-behavior-insights) and noticed that there wasn't a link to the UBI documentation. We should add a link somewhere near the top. Here's the link: https://opensearch.org/docs/latest/search-plugins/ubi/index/.

### How can one reproduce the bug?
check the readme!

### What is the expected behavior?
link to site

### What is your host/environment?
na
### Do you have any screenshots?
na
### Do you have any additional context?
Better docs is a constant process!

**Comment by epugh** [comment]
May not have the inverse either!

**Comment by dblock** [comment]
[Weekly Catch All Triage - [1](https://github.com/dblock)]

@epugh Does this belong in documentation-website?

**Comment by epugh** [comment]
Umm..    Good question..   i had sort of assumed the documentation-website is for changes in the actual repo itself, but since this is really about improving documentation period, it could be (especially if that is the pattern).
Having said that, why don't I get this one sorted this week and we can just close the issue???   ;-).
