### ISSUE TITLE
[FEATURE] Ability to send queries as OTel signals to Data Prepper

### ISSUE THREAD

**Issue by jzonthemtn** [opensearch-project/user-behavior-insights#20]
The UBI plugin should be able to send queries as OTel signals to Data Prepper.

This will enable integration with common OTel tools already in use by some organizations.

**Comment by epugh** [comment]
This is exciting...   Just a reminder, we need to partner this up with the "Ability to send events as Otel trace events to Data Prepper" ;-)

**Comment by dblock** [comment]
[Weekly Catch All Triage - [1](https://github.com/dblock)]

**Comment by jzonthemtn** [comment]
Being worked on https://github.com/jzonthemtn/user-behavior-insights/tree/20-send-otel.

**Comment by jzonthemtn** [comment]
Needs cleaned up and then ready for a pull request.
