### ISSUE TITLE
[FEATURE] Handle multisearch requests

### ISSUE THREAD

**Issue by jzonthemtn** [opensearch-project/user-behavior-insights#29]
### Is your feature request related to a problem?
Currently, the plugin only handles requests of type `SearchRequest`. The plugin should also handle `MultiSearchRequest` objects.

### What solution would you like?
Modify the action filter to handle `MultiSearchRequest`s. Handle each `SearchRequest` in the `MultiSearchRequest` in the same way the plugin does now.

**Comment by epugh** [comment]
I recently complained about the lack of Multi-Search support for pipelines, and made the bold statement "We need to make sure everything supports Multi-Search or we should Deprecate it or rename it 'Dashboard Search'.".   Now, in finding this issue with the plugin I contributed to, I am "hoist on my own petard" ;-).   So let's make sure UBI supports Multi-Search!  cc @msfroh ;-)

**Comment by sandeshkr419** [comment]
[Search Triage] - The group has the opinion that the gaps (if any) in design with multi-seach should be discussed further in OpenSearch repo as well. @epugh @jainankitk to initiate the discussion with an initial draft.
