### ISSUE TITLE
[BUG] Inconsistency between ubi_queries index mappings and implementation to store the ids of the returned docs

### ISSUE THREAD

**Issue by wrigleyDan** [opensearch-project/user-behavior-insights#68]
### What is the bug?
The mappings say the field is called `query_response_hit_ids` (see https://github.com/opensearch-project/user-behavior-insights/blob/main/src/main/resources/queries-mapping.json#L8) while the implementation stores the ids in the field `query_response_object_ids` (see https://github.com/opensearch-project/user-behavior-insights/blob/main/src/main/java/org/opensearch/ubi/UbiActionFilter.java#L238)

### How can one reproduce the bug?
With Chorus running, run a keyword search for laptop, go to OpenSearch Dashboards and look for the latest events in the `ubi_queries` index. You'll see the returned document ids stored in the field `query_response_object_ids`.

Now check the mapping and you'll see that this field is not defined in the mappings. The field present is called `query_response_hit_ids`

### What is the expected behavior?
Either the implementation or the mappings are wrong.

### What is your host/environment?
OS 2.18, plugin version 2.18.0.1

**Comment by jzonthemtn** [comment]
Thanks @wrigleyDan. Good catch. I made a PR #69 to make the code match the mapping.
